### ISSUE TITLE
Can we have this project in the Julia registries?

### ISSUE THREAD

**Issue by PyDataBlog** [leferrad/OCReract.jl#2]
It would be nice to install this project from the official registries. Is that planned?

**Comment by leferrad** [comment]
In fact, that is in progress: https://github.com/JuliaRegistries/General/pull/15264
From the checks, everything seems to be fine for the merge. Once it is done, I will update the documentation in terms of the installation. Glad you asked!

**Comment by leferrad** [comment]
Package was merged so now it is available for Julia 1.4. However, it could be compatible with Julia 1.0+, so that is being fixed in #3. Then I will be registered again, so we can close this issue.

**Comment by PyDataBlog** [comment]
I'm on the latest version so all good. Thanks for the release.

**Comment by leferrad** [comment]
Latest v1.0.1 was merged to General registries, which is now compatible with Julia 1.0+.
More details here: https://github.com/JuliaRegistries/General/pull/15502
