### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by timholy** [leferrad/OCReract.jl#22]
Would it be possible to get a new release? I notice the released version is still pulling in Images.jl, which is heavier than needed.

**Comment by leferrad** [comment]
Sorry for the delay on this @timholy. I was working with #20 but given I don't have an exact solution so far, let's proceed with a new release first. I've opened #23 for that reason, so if nothing else should be added I can merge it and release a new version. Thanks for the heads up!

**Comment by leferrad** [comment]
Given #23 was merged and the Release v1.3.0 (https://github.com/leferrad/OCReract.jl/releases/tag/1.3.0) was created and registered (https://github.com/JuliaRegistries/General/pull/71317), this issue can be closed.

**Comment by timholy** [comment]
Thanks!
