### ISSUE TITLE
Option to return confidence levels?

### ISSUE THREAD

**Issue by dustyirwin** [leferrad/OCReract.jl#7]
Hi, I am wondering if there is a way to return the per-character prediction confidence? I couldn't find anything related to confidence levels in the docs. If I've missed something, please let me know. 

There was an issue posted about this at https://github.com/ropensci/tesseract/issues/8 and was resolved by using calling the `ocr_data()` function or otherwise set HOCR = TRUE in ocr().

Is there an equivalent approach to this in OCReract?

**Comment by leferrad** [comment]
Hi @dustyirwin, nice catch on this! I think we could simply add a way to specify values for config variables with the parameter `-c` as the tesseract's docs suggest:
```
OCR options:
  --tessdata-dir PATH   Specify the location of tessdata path.
  --user-words PATH     Specify the location of user words file.
  --user-patterns PATH  Specify the location of user patterns file.
  -l LANG[+LANG]        Specify language(s) used for OCR.
  -c VAR=VALUE          Set value for config variables.
                        Multiple -c arguments are allowed.
  --psm NUM             Specify page segmentation mode.
  --oem NUM             Specify OCR Engine mode.
```
So in that case, your issue could be tackled by setting `HOCR=TRUE` on the call.
Let me know if that sounds good for you and we can start a PR for this change.

**Comment by leferrad** [comment]
Solved in PR #9. Thanks for your contribution!

**Comment by dustyirwin** [comment]
Thanks for adding the -c config variables! It appears that a couple of flags, `tessedit_create_hocr` & `tessedit_create_tsv`, in particular (there may be more) that modify the extension added by tesseract to the output file. 

The hocr output flag adds ".hocr" and the tsv flag adds the ".tsv" extension. In order to adjust for this I made the following changes to lines 215-232 of tesseract.jl:

```
txt = ""    kwargs_dict = Dict(kwargs)
    cfg_ext = if :tessedit_create_hocr in keys(kwargs_dict)
        ".hocr"
    elseif :tessedit_create_tsv in keys(kwargs_dict)
        ".tsv"
    else
        ""
    end

    open(output_path * cfg_ext, "r") do f
        txt = read(f, String)
    end

    # Now remove these temporary files generated
    try
        @debug "Removing temporary files generated..."
        rm(input_path)
        rm(output_path * cfg_ext)
```

Probably not the most elegant approach, but it has been working for me. :)

**Comment by leferrad** [comment]
I think for those more complex cases when the output is not just a plain text file, it is convenient to use this library just as a wrapper for the command (`run_tesseract(input_path, output_path, ...)`) and then read the generated output according to the specified format, so your solution is correct for what you need.
